"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Oracle__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Oracle__factory_1 = require("./Oracle__factory");
Object.defineProperty(exports, "Oracle__factory", { enumerable: true, get: function () { return Oracle__factory_1.Oracle__factory; } });
